In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

### Read the datasets

In [ ]:
import pandas
ha_df = pandas.read_csv("/content/drive/My Drive/datasets/ha.csv")
hb_df = pandas.read_csv("/content/drive/My Drive/datasets/hb.csv")
hc_df = pandas.read_csv("/content/drive/My Drive/datasets/hc.csv")
hd_df = pandas.read_csv("/content/drive/My Drive/datasets/hd.csv")

In [ ]:
ha_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1923 entries, 0 to 1922
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(13), int64(8), object(124)
memory usage: 2.1+ MB

In [ ]:
hb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(38), int64(9), object(98)
memory usage: 1011.7+ KB

In [ ]:
hc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2458 entries, 0 to 2457
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(22), int64(9), object(114)
memory usage: 2.7+ MB

In [ ]:
hd_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 883 entries, 0 to 882
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(42), int64(13), object(90)
memory usage: 1000.4+ KB

### Concatenating the datasets

In [ ]:
c_df = pandas.concat([ha_df, hb_df, hc_df, hd_df], ignore_index=True)
c_df

,AGE,COUPLESITUATION,HEIGHT,WEIGHT,BMI,COUNTRYOFORIGYN,MATERNALEDUCATION,STARTANTENATALCARRE,SUBSTANCEABUSE,SMOKING,...,HEMATOMALDRAINAGE,INTRAPARTUMpHvalue,sexfetus1,weightfetus1,apgarfetus1,apgarfetus1fivemin,pHvaluefetus1umbilicalarthery,FETUS1ADMISSIONICU,FETUS1RECOVERY,FETUS1MECONIUMASPIRATIONSYNDROME
0,30,withcouple,1.58,70.0,28.04,CHILE,secondary,1ºtrimester,f,f,...,NaN,NaN,Masculino,2640,7,9,7.34,f,1:Aspiraciónnasofaríngea,f
1,38,withcouple,1.61,79.0,30.48,ESPAÑA,secondary,1ºtrimester,f,f,...,NaN,NaN,Femenino,3040,8,9,7.26,f,0:noprecisa,f
2,25,withcouple,1.56,72.0,29.59,COLOMBIA,secondary,1ºtrimester,f,f,...,NaN,NaN,Femenino,3820,10,10,7.21,f,0:noprecisa,f
3,31,withcouple,1.62,54.0,20.58,ESPAÑA,secondary,1ºtrimester,f,f,...,NaN,NaN,Femenino,3390,9,10,7.21,f,0:noprecisa,f
4,28,withcouple,1.47,51.0,23.60,ESPAÑA,secondary,1ºtrimester,f,f,...,NaN,NaN,Masculino,3020,8,9,7.17,f,0:noprecisa,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6152,35,withcouple,1.56,49.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,1960,10,10,7.27,f,NaN,f,NaN,NaN,NaN
6153,29,withcouple,1.64,59.0,21.51,ESPAÑA,secondary,1ºtrimester,f,f,...,3310,9,10,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN
6154,39,withcouple,1.59,64.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,3830,8,9,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN
6155,41,withcouple,1.48,50.0,23.28,ESPAÑA,primary,1ºtrimester,f,f,...,2810,10,10,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN
6156,32,withcouple,1.65,75.2,24.00,ARGELIA,Sinestudios,1ºtrimester,f,f,...,3160,10,10,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN

### Information of the concatenated dataset

In [ ]:
c_df.info(145)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6157 entries, 0 to 6156
Data columns (total 145 columns):
 #    Column                                  Dtype
---   ------                                  -----
 0    AGE                                     int64
 1    COUPLESITUATION                         object
 2    HEIGHT                                  float64
 3    WEIGHT                                  float64
 4    BMI                                     float64
 5    COUNTRYOFORIGYN                         object
 6    MATERNALEDUCATION                       object
 7    STARTANTENATALCARRE                     object
 8    SUBSTANCEABUSE                          object
 9    SMOKING                                 object
 10   CIGARRETTESPERDAY                       float64
 11   ALCOHOL                                 object
 12   DAILYALCOHOLINTAKE                      object
 13   KGINCREASEDPREGNANCY                    int64
 14   ART                                     object
 15   ARTMODE                                 object
 16   AMNIOCENTESIS                           object
 17   PREVIOUSCESAREAN                        object
 18   NUMBEROFPREVCESAREAN                    float64
 19   COMORBIDITY                             object
 20   OBSTETRICRISK                           object
 21   PREVIOUSTERMPREGNANCIES                 int64
 22   PREVIOUSPRETERMPREGNANCIES              int64
 23   MISCARRIAGES                            int64
 24   ALIVENEWBORNS                           int64
 25   PARITY                                  int64
 26   PREINDUCTION                            object
 27   INDUCTION                               object
 28   HOURSROMBEFOREINDUCTION                 object
 29   ANESTHESIA                              object
 30   HOURSOFRUPTUREDMEMBRANESATDELIVERY      object
 31   GESTAGIONALAGE                          int64
 32   CARDIOTOCOGRAPHY                        object
 33   TYPEOFBIRTH                             object
 34   EPISIOTOMY                              object
 35   TEAR                                    object
 36   MEDICALINDICATION                       object
 37   EMERGENCYCESAREANSECTION                object
 38   PROGRAMMEDCESAREANSECTION               object
 39   OXYTOCIN                                object
 40   AMNIOTICLIQUID                          object
 41   FetalINTRAPARTUMpH                      object
 42   COMPLICATIONS                           object
 43   ROBSONGROUP                             object
 44   CESAREANINACCORDANCETOCLINICALSTANDARD  object
 45   COLESTASISGRAVIDICA                     object
 46   CORIONAMNIONITIS                        object
 47   NONIDGESTATIONALDIABETES                object
 48   IDGESTATIONALDIABETES                   object
 49   PROLONGEDPREGNANACY                     object
 50   MULTIPLEGESTATION                       object
 51   HELLP                                   object
 52   GESTATIONALHYPERTENSION                 object
 53   ISOINMUNIZACION                         object
 54   STAINEDAMNIOTICLIQUOR                   object
 55   FETALMALFORMATION                       object
 56   UTERINEMALFORMATION                     object
 57   FETALMALPOSITION                        object
 58   MIOMECTOMY                              object
 59   OLIGOAMNIOS                             object
 60   PREVIOUSPRETERMDELIVERY                 object
 61   PLACENTAPREVIA                          object
 62   POLIHIDRAMNIOS                          object
 63   SEVEREPREECLAMPSIA                      object
 64   MILDPREECLAMPSIA                        object
 65   PROM                                    object
 66   SIFILIS                                 object
 67   TOXOPLASMOSIS                           object
 68   REPEATEDMISCARRIAGES                    object
 69   PREVIOUSFETALLOSSES                     object
 70   ANTEPARTUMLOSSOFFETALWELLBEEING         object
 71   MATERNALANEMIA                          object
 72   ASTHMA                                  object
 73   CARDIACDISEASE                          object
 74   Coagulopathy                            object
 75   PREGESTATIONALTYPEIDIABETES             object
 76   PREGESTATIONALTYPEIIDIABETES            object
 77   AUTOINMUNEDISEASEINTREATMENT            object
 78   EPILEPSYINTREATMENT                     object
 79   MENTALDISEASEINTREATMENT                object
 80   NEUROLOGICALDISEASEINTREATMENT          object
 81   RENALDISEASEINTREATMENT                 object
 82   Hemiplegia                              object
 83   LIVERDISEASEINTREATMENT                 object
 84   HIPERTHYROIDISMINTREATMENT              object
 85   HIPOTHYROIDISMINTREATMENT               object
 86   HIV+                                    object
 87   CHRONICHYPERTENSION                     object
 88   TIP                                     object
 89   MALIGNANTTUMOR                          object
 90   HVC+                                    object
 91   HVB+                                    object
 92   CORIONICBIOPSY                          object
 93   Cordocentesis                           float64
 94   Cannabis                                object
 95   COCCAINE                                object
 96   Heroin                                  object
 97   others                                  object
 98   IUGR                                    object
 99   Colestasis                              object
 100  Diabetes                                object
 101  ABNORMALDOPPLER                         object
 102  ExitusFetal                             object
 103  STAINEDAMNIOTICLIQUID                   object
 104  NONCONFIDENTNST                         object
 105  Oligoamnios                             object
 106  MATERNALDISEASE                         object
 107  SGD                                     object
 108  Preeclampsia                            object
 109  PROM.1                                  object
 110  INITIALPROLONGEDPREGNANCY               object
 111  OTHERS                                  object
 112  LOC                                     object
 113  REG                                     object
 114  GEN                                     object
 115  UTERINEATONY                            object
 116  AMNIOTICLIQUIDEMBOLISM                  float64
 117  PERINEALHEMATOMA                        object
 118  UTERINEHAEMORRAGE                       object
 119  INVERTEDUTERUS                          object
 120  MATERNALDEATH                           object
 121  RETAINEDPLACENTA                        object
 122  UTERINERUPTURE                          object
 123  PULMONARTHROMBOEMBOLISM                 object
 124  DEEPVENOUSTHROMBOSIS                    object
 125  SHOULDERDYSTOCIA                        object
 126  TEARREPAIR                              object
 127  MANUALEXTRACTIONOFPLACENTA              object
 128  HISTERECTOMY                            object
 129  POSTPARTUMCURETAGE                      object
 130  REPOSITIONOFINVERTEDUTERUS              object
 131  BLOODTRANSFUSION                        object
 132  MEDICALTREATMENT                        object
 133  MANUALASSITANCETOSHOULDERDYSTOCIA       object
 134  ARTHERIALEMBOLIZATION                   object
 135  HEMATOMALDRAINAGE                       object
 136  INTRAPARTUMpHvalue                      object
 137  sexfetus1                               object
 138  weightfetus1                            object
 139  apgarfetus1                             object
 140  apgarfetus1fivemin                      object
 141  pHvaluefetus1umbilicalarthery           object
 142  FETUS1ADMISSIONICU                      object
 143  FETUS1RECOVERY                          object
 144  FETUS1MECONIUMASPIRATIONSYNDROME        object
dtypes: float64(7), int64(8), object(130)
memory usage: 6.8+ MB

### Checking missing values

In [ ]:
c_df.isnull().sum()

AGE                                    0
COUPLESITUATION                        0
HEIGHT                                 0
WEIGHT                                 0
BMI                                    0
                                    ...
apgarfetus1fivemin                  4219
pHvaluefetus1umbilicalarthery          0
FETUS1ADMISSIONICU                  4238
FETUS1RECOVERY                      4235
FETUS1MECONIUMASPIRATIONSYNDROME    4234
Length: 145, dtype: int64

### Class labels

In [ ]:
c_df.TYPEOFBIRTH.unique()

array(['emergencyc-section', 'CESprogrammed', 'EUT', 'vacum', 'FORC',
       'ESP', 'NALGASVAGINAL'], dtype=object)

In [ ]:
a = c_df['TYPEOFBIRTH'].values.tolist()
s = set(a)
for x in s:
  print(x,":",a.count(x))

NALGASVAGINAL : 8
FORC : 87
ESP : 44
emergencyc-section : 692
EUT : 4231
vacum : 770
CESprogrammed : 325

### Preprocessing

### Dataset after feature extraction

### Checking duplicates

In [ ]:
c_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
6152    False
6153    False
6154    False
6155    False
6156    False
Length: 6157, dtype: bool

In [ ]:
c_df.duplicated().sum()

11

### Drop duplicate records

In [ ]:
new_df1 = c_df.drop_duplicates()
new_df1

,AGE,COUPLESITUATION,HEIGHT,WEIGHT,BMI,COUNTRYOFORIGYN,MATERNALEDUCATION,STARTANTENATALCARRE,SUBSTANCEABUSE,SMOKING,...,HEMATOMALDRAINAGE,INTRAPARTUMpHvalue,sexfetus1,weightfetus1,apgarfetus1,apgarfetus1fivemin,pHvaluefetus1umbilicalarthery,FETUS1ADMISSIONICU,FETUS1RECOVERY,FETUS1MECONIUMASPIRATIONSYNDROME
0,30,withcouple,1.58,70.0,28.04,CHILE,secondary,1ºtrimester,f,f,...,NaN,NaN,Masculino,2640,7,9,7.34,f,1:Aspiraciónnasofaríngea,f
1,38,withcouple,1.61,79.0,30.48,ESPAÑA,secondary,1ºtrimester,f,f,...,NaN,NaN,Femenino,3040,8,9,7.26,f,0:noprecisa,f
2,25,withcouple,1.56,72.0,29.59,COLOMBIA,secondary,1ºtrimester,f,f,...,NaN,NaN,Femenino,3820,10,10,7.21,f,0:noprecisa,f
3,31,withcouple,1.62,54.0,20.58,ESPAÑA,secondary,1ºtrimester,f,f,...,NaN,NaN,Femenino,3390,9,10,7.21,f,0:noprecisa,f
4,28,withcouple,1.47,51.0,23.60,ESPAÑA,secondary,1ºtrimester,f,f,...,NaN,NaN,Masculino,3020,8,9,7.17,f,0:noprecisa,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6152,35,withcouple,1.56,49.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,1960,10,10,7.27,f,NaN,f,NaN,NaN,NaN
6153,29,withcouple,1.64,59.0,21.51,ESPAÑA,secondary,1ºtrimester,f,f,...,3310,9,10,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN
6154,39,withcouple,1.59,64.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,3830,8,9,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN
6155,41,withcouple,1.48,50.0,23.28,ESPAÑA,primary,1ºtrimester,f,f,...,2810,10,10,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN
6156,32,withcouple,1.65,75.2,24.00,ARGELIA,Sinestudios,1ºtrimester,f,f,...,3160,10,10,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN

In [ ]:
import numpy as np
new_df1 = new_df1.replace(r'^\s*$', np.nan, regex=True)

### Handling missing values of categorical attributes by mode

In [ ]:
s = (new_df1.dtypes == 'object')
#print(s)
#print(s[s])
object_cols = list(s[s].index)
print("Categorical variables:")
print(object_cols)
print(len(object_cols))

Categorical variables:
['COUPLESITUATION', 'COUNTRYOFORIGYN', 'MATERNALEDUCATION', 'STARTANTENATALCARRE', 'SUBSTANCEABUSE', 'SMOKING', 'ALCOHOL', 'DAILYALCOHOLINTAKE', 'ART', 'ARTMODE', 'AMNIOCENTESIS', 'PREVIOUSCESAREAN', 'COMORBIDITY', 'OBSTETRICRISK', 'PREINDUCTION', 'INDUCTION', 'HOURSROMBEFOREINDUCTION', 'ANESTHESIA', 'HOURSOFRUPTUREDMEMBRANESATDELIVERY', 'CARDIOTOCOGRAPHY', 'TYPEOFBIRTH', 'EPISIOTOMY', 'TEAR', 'MEDICALINDICATION', 'EMERGENCYCESAREANSECTION', 'PROGRAMMEDCESAREANSECTION', 'OXYTOCIN', 'AMNIOTICLIQUID', 'FetalINTRAPARTUMpH', 'COMPLICATIONS', 'ROBSONGROUP', 'CESAREANINACCORDANCETOCLINICALSTANDARD', 'COLESTASISGRAVIDICA', 'CORIONAMNIONITIS', 'NONIDGESTATIONALDIABETES', 'IDGESTATIONALDIABETES', 'PROLONGEDPREGNANACY', 'MULTIPLEGESTATION', 'HELLP', 'GESTATIONALHYPERTENSION', 'ISOINMUNIZACION', 'STAINEDAMNIOTICLIQUOR', 'FETALMALFORMATION', 'UTERINEMALFORMATION', 'FETALMALPOSITION', 'MIOMECTOMY', 'OLIGOAMNIOS', 'PREVIOUSPRETERMDELIVERY', 'PLACENTAPREVIA', 'POLIHIDRAMNIOS', 'SEVEREPREECLAMPSIA', 'MILDPREECLAMPSIA', 'PROM', 'SIFILIS', 'TOXOPLASMOSIS', 'REPEATEDMISCARRIAGES', 'PREVIOUSFETALLOSSES', 'ANTEPARTUMLOSSOFFETALWELLBEEING', 'MATERNALANEMIA', 'ASTHMA', 'CARDIACDISEASE', 'Coagulopathy', 'PREGESTATIONALTYPEIDIABETES', 'PREGESTATIONALTYPEIIDIABETES', 'AUTOINMUNEDISEASEINTREATMENT', 'EPILEPSYINTREATMENT', 'MENTALDISEASEINTREATMENT', 'NEUROLOGICALDISEASEINTREATMENT', 'RENALDISEASEINTREATMENT', 'Hemiplegia', 'LIVERDISEASEINTREATMENT', 'HIPERTHYROIDISMINTREATMENT', 'HIPOTHYROIDISMINTREATMENT', 'HIV+', 'CHRONICHYPERTENSION', 'TIP', 'MALIGNANTTUMOR', 'HVC+', 'HVB+', 'CORIONICBIOPSY', 'Cannabis', 'COCCAINE', 'Heroin', 'others', 'IUGR', 'Colestasis', 'Diabetes', 'ABNORMALDOPPLER', 'ExitusFetal', 'STAINEDAMNIOTICLIQUID', 'NONCONFIDENTNST', 'Oligoamnios', 'MATERNALDISEASE', 'SGD', 'Preeclampsia', 'PROM.1', 'INITIALPROLONGEDPREGNANCY', 'OTHERS', 'LOC', 'REG', 'GEN', 'UTERINEATONY', 'PERINEALHEMATOMA', 'UTERINEHAEMORRAGE', 'INVERTEDUTERUS', 'MATERNALDEATH', 'RETAINEDPLACENTA', 'UTERINERUPTURE', 'PULMONARTHROMBOEMBOLISM', 'DEEPVENOUSTHROMBOSIS', 'SHOULDERDYSTOCIA', 'TEARREPAIR', 'MANUALEXTRACTIONOFPLACENTA', 'HISTERECTOMY', 'POSTPARTUMCURETAGE', 'REPOSITIONOFINVERTEDUTERUS', 'BLOODTRANSFUSION', 'MEDICALTREATMENT', 'MANUALASSITANCETOSHOULDERDYSTOCIA', 'ARTHERIALEMBOLIZATION', 'HEMATOMALDRAINAGE', 'INTRAPARTUMpHvalue', 'sexfetus1', 'weightfetus1', 'apgarfetus1', 'apgarfetus1fivemin', 'pHvaluefetus1umbilicalarthery', 'FETUS1ADMISSIONICU', 'FETUS1RECOVERY', 'FETUS1MECONIUMASPIRATIONSYNDROME']
130

In [ ]:
for i in object_cols:
  x = new_df1[i].mode()[0]
  new_df1[i].fillna(x,inplace = True)
new_df1

,AGE,COUPLESITUATION,HEIGHT,WEIGHT,BMI,COUNTRYOFORIGYN,MATERNALEDUCATION,STARTANTENATALCARRE,SUBSTANCEABUSE,SMOKING,...,HEMATOMALDRAINAGE,INTRAPARTUMpHvalue,sexfetus1,weightfetus1,apgarfetus1,apgarfetus1fivemin,pHvaluefetus1umbilicalarthery,FETUS1ADMISSIONICU,FETUS1RECOVERY,FETUS1MECONIUMASPIRATIONSYNDROME
0,30,withcouple,1.58,70.0,28.04,CHILE,secondary,1ºtrimester,f,f,...,3200,9,Masculino,2640,7,9,7.34,f,1:Aspiraciónnasofaríngea,f
1,38,withcouple,1.61,79.0,30.48,ESPAÑA,secondary,1ºtrimester,f,f,...,3200,9,Femenino,3040,8,9,7.26,f,0:noprecisa,f
2,25,withcouple,1.56,72.0,29.59,COLOMBIA,secondary,1ºtrimester,f,f,...,3200,9,Femenino,3820,10,10,7.21,f,0:noprecisa,f
3,31,withcouple,1.62,54.0,20.58,ESPAÑA,secondary,1ºtrimester,f,f,...,3200,9,Femenino,3390,9,10,7.21,f,0:noprecisa,f
4,28,withcouple,1.47,51.0,23.60,ESPAÑA,secondary,1ºtrimester,f,f,...,3200,9,Masculino,3020,8,9,7.17,f,0:noprecisa,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6152,35,withcouple,1.56,49.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,1960,10,10,7.27,f,10,f,f,0:noprecisa,f
6153,29,withcouple,1.64,59.0,21.51,ESPAÑA,secondary,1ºtrimester,f,f,...,3310,9,10,DESCONOCIDO,f,10,f,f,0:noprecisa,f
6154,39,withcouple,1.59,64.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,3830,8,9,DESCONOCIDO,f,10,f,f,0:noprecisa,f
6155,41,withcouple,1.48,50.0,23.28,ESPAÑA,primary,1ºtrimester,f,f,...,2810,10,10,DESCONOCIDO,f,10,f,f,0:noprecisa,f
6156,32,withcouple,1.65,75.2,24.00,ARGELIA,Sinestudios,1ºtrimester,f,f,...,3160,10,10,DESCONOCIDO,f,10,f,f,0:noprecisa,f

### Handling missing values of Numerical attributes using mean

In [ ]:
s = (new_df1.dtypes != 'object')
number_cols = list(s[s].index)
print("Numerical variables:")
print(number_cols)
print(len(number_cols))

Numerical variables:
['AGE', 'HEIGHT', 'WEIGHT', 'BMI', 'CIGARRETTESPERDAY', 'KGINCREASEDPREGNANCY', 'NUMBEROFPREVCESAREAN', 'PREVIOUSTERMPREGNANCIES', 'PREVIOUSPRETERMPREGNANCIES', 'MISCARRIAGES', 'ALIVENEWBORNS', 'PARITY', 'GESTAGIONALAGE', 'Cordocentesis', 'AMNIOTICLIQUIDEMBOLISM']
15

In [ ]:
for i in number_cols:
  x = new_df1[i].mean()
  new_df1[i].fillna(x,inplace = True)
new_df1

,AGE,COUPLESITUATION,HEIGHT,WEIGHT,BMI,COUNTRYOFORIGYN,MATERNALEDUCATION,STARTANTENATALCARRE,SUBSTANCEABUSE,SMOKING,...,HEMATOMALDRAINAGE,INTRAPARTUMpHvalue,sexfetus1,weightfetus1,apgarfetus1,apgarfetus1fivemin,pHvaluefetus1umbilicalarthery,FETUS1ADMISSIONICU,FETUS1RECOVERY,FETUS1MECONIUMASPIRATIONSYNDROME
0,30,withcouple,1.58,70.0,28.04,CHILE,secondary,1ºtrimester,f,f,...,3200,9,Masculino,2640,7,9,7.34,f,1:Aspiraciónnasofaríngea,f
1,38,withcouple,1.61,79.0,30.48,ESPAÑA,secondary,1ºtrimester,f,f,...,3200,9,Femenino,3040,8,9,7.26,f,0:noprecisa,f
2,25,withcouple,1.56,72.0,29.59,COLOMBIA,secondary,1ºtrimester,f,f,...,3200,9,Femenino,3820,10,10,7.21,f,0:noprecisa,f
3,31,withcouple,1.62,54.0,20.58,ESPAÑA,secondary,1ºtrimester,f,f,...,3200,9,Femenino,3390,9,10,7.21,f,0:noprecisa,f
4,28,withcouple,1.47,51.0,23.60,ESPAÑA,secondary,1ºtrimester,f,f,...,3200,9,Masculino,3020,8,9,7.17,f,0:noprecisa,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6152,35,withcouple,1.56,49.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,1960,10,10,7.27,f,10,f,f,0:noprecisa,f
6153,29,withcouple,1.64,59.0,21.51,ESPAÑA,secondary,1ºtrimester,f,f,...,3310,9,10,DESCONOCIDO,f,10,f,f,0:noprecisa,f
6154,39,withcouple,1.59,64.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,3830,8,9,DESCONOCIDO,f,10,f,f,0:noprecisa,f
6155,41,withcouple,1.48,50.0,23.28,ESPAÑA,primary,1ºtrimester,f,f,...,2810,10,10,DESCONOCIDO,f,10,f,f,0:noprecisa,f
6156,32,withcouple,1.65,75.2,24.00,ARGELIA,Sinestudios,1ºtrimester,f,f,...,3160,10,10,DESCONOCIDO,f,10,f,f,0:noprecisa,f

In [ ]:
new_df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6146 entries, 0 to 6156
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(7), int64(8), object(130)
memory usage: 6.8+ MB

### Checking NULL values

In [ ]:
new_df1.isnull().sum()

AGE                                 0
COUPLESITUATION                     0
HEIGHT                              0
WEIGHT                              0
BMI                                 0
                                   ..
apgarfetus1fivemin                  0
pHvaluefetus1umbilicalarthery       0
FETUS1ADMISSIONICU                  0
FETUS1RECOVERY                      0
FETUS1MECONIUMASPIRATIONSYNDROME    0
Length: 145, dtype: int64

In [ ]:
new_df1.TYPEOFBIRTH.unique()

array(['emergencyc-section', 'CESprogrammed', 'EUT', 'vacum', 'FORC',
       'ESP', 'NALGASVAGINAL'], dtype=object)

In [ ]:
a = new_df1['TYPEOFBIRTH'].values.tolist()
s = set(a)
for x in s:
  print(x,":",a.count(x))

NALGASVAGINAL : 8
FORC : 87
ESP : 44
emergencyc-section : 690
EUT : 4226
vacum : 766
CESprogrammed : 325

In [ ]:
new_df1

,AGE,COUPLESITUATION,HEIGHT,WEIGHT,BMI,COUNTRYOFORIGYN,MATERNALEDUCATION,STARTANTENATALCARRE,SUBSTANCEABUSE,SMOKING,...,HEMATOMALDRAINAGE,INTRAPARTUMpHvalue,sexfetus1,weightfetus1,apgarfetus1,apgarfetus1fivemin,pHvaluefetus1umbilicalarthery,FETUS1ADMISSIONICU,FETUS1RECOVERY,FETUS1MECONIUMASPIRATIONSYNDROME
0,30,withcouple,1.58,70.0,28.04,CHILE,secondary,1ºtrimester,f,f,...,3200,9,Masculino,2640,7,9,7.34,f,1:Aspiraciónnasofaríngea,f
1,38,withcouple,1.61,79.0,30.48,ESPAÑA,secondary,1ºtrimester,f,f,...,3200,9,Femenino,3040,8,9,7.26,f,0:noprecisa,f
2,25,withcouple,1.56,72.0,29.59,COLOMBIA,secondary,1ºtrimester,f,f,...,3200,9,Femenino,3820,10,10,7.21,f,0:noprecisa,f
3,31,withcouple,1.62,54.0,20.58,ESPAÑA,secondary,1ºtrimester,f,f,...,3200,9,Femenino,3390,9,10,7.21,f,0:noprecisa,f
4,28,withcouple,1.47,51.0,23.60,ESPAÑA,secondary,1ºtrimester,f,f,...,3200,9,Masculino,3020,8,9,7.17,f,0:noprecisa,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6152,35,withcouple,1.56,49.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,1960,10,10,7.27,f,10,f,f,0:noprecisa,f
6153,29,withcouple,1.64,59.0,21.51,ESPAÑA,secondary,1ºtrimester,f,f,...,3310,9,10,DESCONOCIDO,f,10,f,f,0:noprecisa,f
6154,39,withcouple,1.59,64.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,3830,8,9,DESCONOCIDO,f,10,f,f,0:noprecisa,f
6155,41,withcouple,1.48,50.0,23.28,ESPAÑA,primary,1ºtrimester,f,f,...,2810,10,10,DESCONOCIDO,f,10,f,f,0:noprecisa,f
6156,32,withcouple,1.65,75.2,24.00,ARGELIA,Sinestudios,1ºtrimester,f,f,...,3160,10,10,DESCONOCIDO,f,10,f,f,0:noprecisa,f

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

#new_df1.Publisher = new_df1.Publisher.astype(str)

for column in new_df1.columns:
    temp_new = le.fit_transform(new_df1[column].astype(str))
    new_df1.drop(labels=[column], axis="columns", inplace=True)
    new_df1[column] = temp_new

X = new_df1.drop(['TYPEOFBIRTH'],axis=1)
Y = new_df1['TYPEOFBIRTH']

In [ ]:
#@title Default title text
##from imblearn.over_sampling import SMOTE
##oversample = SMOTE()
##X_smote, Y_smote = oversample.fit_resample(X, Y)
##print(X_smote.shape)
##print(Y_smote.shape)

In [ ]:
from imblearn.over_sampling import ADASYN 
sm = ADASYN(sampling_strategy='auto', random_state=None, n_neighbors=5, n_jobs=1)
X_adassin_1, Y_adassin_1 = sm.fit_resample(X, Y)
print(X_adassin_1.shape)
print(Y_adassin_1.shape)

(29342, 144)
(29342,)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_adassin_1,Y_adassin_1,test_size=0.2,random_state=None)

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23473 entries, 3202 to 16812
Columns: 144 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: int64(144)
memory usage: 26.0 MB

In [ ]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5869 entries, 23647 to 4054
Columns: 144 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: int64(144)
memory usage: 6.5 MB

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
model = DecisionTreeClassifier(criterion = 'entropy')
model.fit(X_train,Y_train)
y_pred = model.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

0.9299710342477424
0.9288054973464426
0.9299710342477424
0.9299710342477424

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier()
RFC.fit(X_train, Y_train.values.ravel())
y_pred = RFC.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

0.9681376725166128
0.9685659065256722
0.9681376725166128
0.9681376725166128

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
svc = SVC(gamma = 0.001, C = 1000)
y_pred = svc.fit(X_train, Y_train.values.ravel()).predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

0.9528028624978702
0.952628919359156
0.9528028624978702
0.9528028624978702

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
K = []
training = []
test = []
scores = {}
  
for k in range(2, 21):
    clf = KNeighborsClassifier(n_neighbors = k)
    clf.fit(X_train, Y_train.values.ravel())
  
    training_score = clf.score(X_train, Y_train)
    test_score = clf.score(X_test, Y_test)
    K.append(k)
  
    training.append(training_score)
    test.append(test_score)
    scores[k] = [training_score, test_score]
for keys, values in scores.items():
    print(keys, ':', values)

2 : [0.9656626762663486, 0.8889078207531096]
3 : [0.9262556980360415, 0.8785142272959618]
4 : [0.913389852170579, 0.861134775941387]
5 : [0.8964768031355174, 0.8575566536036804]
6 : [0.8837813658245643, 0.8417106832509798]
7 : [0.8716823584543945, 0.8323394104617482]
8 : [0.861074425936182, 0.8199011756687681]
9 : [0.8523409875175734, 0.8108706764355086]
10 : [0.8416478507221062, 0.7982620548645425]
11 : [0.8316789502833042, 0.7904242630771852]
12 : [0.8221786733694031, 0.782586471289828]
13 : [0.8143824820005964, 0.777474867950247]
14 : [0.8047543986708132, 0.7692963026069177]
15 : [0.7982788735994547, 0.7635031521553928]
16 : [0.7920163592212329, 0.7571988413699097]
17 : [0.7845183828228177, 0.7498722099165105]
18 : [0.7780854598900865, 0.7442494462429715]
19 : [0.7717803433732373, 0.7369228147895723]
20 : [0.7659438503812891, 0.7324927585619356]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=2,weights='distance',p=1)
model.fit(X_train,Y_train.values.ravel())
y_pred = model.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

0.9260521383540637
0.9305868210490532
0.9260521383540637
0.9260521383540637

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import StackingClassifier
estimators = [('rf', RandomForestClassifier()),('svr', make_pipeline(StandardScaler(),LinearSVC())),('dt',DecisionTreeClassifier(criterion = 'entropy')),('knn',KNeighborsClassifier(n_neighbors=2,weights='distance',p=1))]
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
clf.fit(X_train, Y_train.values.ravel())
y_pred = clf.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

0.9855171238711876
0.9855757284735576
0.9855171238711876
0.9855171238711876

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,