In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

### Read the datasets

In [ ]:
import pandas
ha_df = pandas.read_csv("/content/drive/My Drive/datasets/ha.csv")
hb_df = pandas.read_csv("/content/drive/My Drive/datasets/hb.csv")
hc_df = pandas.read_csv("/content/drive/My Drive/datasets/hc.csv")
hd_df = pandas.read_csv("/content/drive/My Drive/datasets/hd.csv")

In [ ]:
ha_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1923 entries, 0 to 1922
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(13), int64(8), object(124)
memory usage: 2.1+ MB

In [ ]:
hb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(38), int64(9), object(98)
memory usage: 1011.7+ KB

In [ ]:
hc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2458 entries, 0 to 2457
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(22), int64(9), object(114)
memory usage: 2.7+ MB

In [ ]:
hd_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 883 entries, 0 to 882
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(42), int64(13), object(90)
memory usage: 1000.4+ KB

### Concatenating the datasets

In [ ]:
c_df = pandas.concat([ha_df, hb_df, hc_df, hd_df], ignore_index=True)
c_df

,AGE,COUPLESITUATION,HEIGHT,WEIGHT,BMI,COUNTRYOFORIGYN,MATERNALEDUCATION,STARTANTENATALCARRE,SUBSTANCEABUSE,SMOKING,...,HEMATOMALDRAINAGE,INTRAPARTUMpHvalue,sexfetus1,weightfetus1,apgarfetus1,apgarfetus1fivemin,pHvaluefetus1umbilicalarthery,FETUS1ADMISSIONICU,FETUS1RECOVERY,FETUS1MECONIUMASPIRATIONSYNDROME
0,30,withcouple,1.58,70.0,28.04,CHILE,secondary,1ºtrimester,f,f,...,NaN,NaN,Masculino,2640,7,9,7.34,f,1:Aspiraciónnasofaríngea,f
1,38,withcouple,1.61,79.0,30.48,ESPAÑA,secondary,1ºtrimester,f,f,...,NaN,NaN,Femenino,3040,8,9,7.26,f,0:noprecisa,f
2,25,withcouple,1.56,72.0,29.59,COLOMBIA,secondary,1ºtrimester,f,f,...,NaN,NaN,Femenino,3820,10,10,7.21,f,0:noprecisa,f
3,31,withcouple,1.62,54.0,20.58,ESPAÑA,secondary,1ºtrimester,f,f,...,NaN,NaN,Femenino,3390,9,10,7.21,f,0:noprecisa,f
4,28,withcouple,1.47,51.0,23.60,ESPAÑA,secondary,1ºtrimester,f,f,...,NaN,NaN,Masculino,3020,8,9,7.17,f,0:noprecisa,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6152,35,withcouple,1.56,49.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,1960,10,10,7.27,f,NaN,f,NaN,NaN,NaN
6153,29,withcouple,1.64,59.0,21.51,ESPAÑA,secondary,1ºtrimester,f,f,...,3310,9,10,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN
6154,39,withcouple,1.59,64.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,3830,8,9,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN
6155,41,withcouple,1.48,50.0,23.28,ESPAÑA,primary,1ºtrimester,f,f,...,2810,10,10,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN
6156,32,withcouple,1.65,75.2,24.00,ARGELIA,Sinestudios,1ºtrimester,f,f,...,3160,10,10,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN

### Information of the concatenated dataset

In [ ]:
c_df.info(145)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6157 entries, 0 to 6156
Data columns (total 145 columns):
 #    Column                                  Dtype
---   ------                                  -----
 0    AGE                                     int64
 1    COUPLESITUATION                         object
 2    HEIGHT                                  float64
 3    WEIGHT                                  float64
 4    BMI                                     float64
 5    COUNTRYOFORIGYN                         object
 6    MATERNALEDUCATION                       object
 7    STARTANTENATALCARRE                     object
 8    SUBSTANCEABUSE                          object
 9    SMOKING                                 object
 10   CIGARRETTESPERDAY                       float64
 11   ALCOHOL                                 object
 12   DAILYALCOHOLINTAKE                      object
 13   KGINCREASEDPREGNANCY                    int64
 14   ART                                     object
 15   ARTMODE                                 object
 16   AMNIOCENTESIS                           object
 17   PREVIOUSCESAREAN                        object
 18   NUMBEROFPREVCESAREAN                    float64
 19   COMORBIDITY                             object
 20   OBSTETRICRISK                           object
 21   PREVIOUSTERMPREGNANCIES                 int64
 22   PREVIOUSPRETERMPREGNANCIES              int64
 23   MISCARRIAGES                            int64
 24   ALIVENEWBORNS                           int64
 25   PARITY                                  int64
 26   PREINDUCTION                            object
 27   INDUCTION                               object
 28   HOURSROMBEFOREINDUCTION                 object
 29   ANESTHESIA                              object
 30   HOURSOFRUPTUREDMEMBRANESATDELIVERY      object
 31   GESTAGIONALAGE                          int64
 32   CARDIOTOCOGRAPHY                        object
 33   TYPEOFBIRTH                             object
 34   EPISIOTOMY                              object
 35   TEAR                                    object
 36   MEDICALINDICATION                       object
 37   EMERGENCYCESAREANSECTION                object
 38   PROGRAMMEDCESAREANSECTION               object
 39   OXYTOCIN                                object
 40   AMNIOTICLIQUID                          object
 41   FetalINTRAPARTUMpH                      object
 42   COMPLICATIONS                           object
 43   ROBSONGROUP                             object
 44   CESAREANINACCORDANCETOCLINICALSTANDARD  object
 45   COLESTASISGRAVIDICA                     object
 46   CORIONAMNIONITIS                        object
 47   NONIDGESTATIONALDIABETES                object
 48   IDGESTATIONALDIABETES                   object
 49   PROLONGEDPREGNANACY                     object
 50   MULTIPLEGESTATION                       object
 51   HELLP                                   object
 52   GESTATIONALHYPERTENSION                 object
 53   ISOINMUNIZACION                         object
 54   STAINEDAMNIOTICLIQUOR                   object
 55   FETALMALFORMATION                       object
 56   UTERINEMALFORMATION                     object
 57   FETALMALPOSITION                        object
 58   MIOMECTOMY                              object
 59   OLIGOAMNIOS                             object
 60   PREVIOUSPRETERMDELIVERY                 object
 61   PLACENTAPREVIA                          object
 62   POLIHIDRAMNIOS                          object
 63   SEVEREPREECLAMPSIA                      object
 64   MILDPREECLAMPSIA                        object
 65   PROM                                    object
 66   SIFILIS                                 object
 67   TOXOPLASMOSIS                           object
 68   REPEATEDMISCARRIAGES                    object
 69   PREVIOUSFETALLOSSES                     object
 70   ANTEPARTUMLOSSOFFETALWELLBEEING         object
 71   MATERNALANEMIA                          object
 72   ASTHMA                                  object
 73   CARDIACDISEASE                          object
 74   Coagulopathy                            object
 75   PREGESTATIONALTYPEIDIABETES             object
 76   PREGESTATIONALTYPEIIDIABETES            object
 77   AUTOINMUNEDISEASEINTREATMENT            object
 78   EPILEPSYINTREATMENT                     object
 79   MENTALDISEASEINTREATMENT                object
 80   NEUROLOGICALDISEASEINTREATMENT          object
 81   RENALDISEASEINTREATMENT                 object
 82   Hemiplegia                              object
 83   LIVERDISEASEINTREATMENT                 object
 84   HIPERTHYROIDISMINTREATMENT              object
 85   HIPOTHYROIDISMINTREATMENT               object
 86   HIV+                                    object
 87   CHRONICHYPERTENSION                     object
 88   TIP                                     object
 89   MALIGNANTTUMOR                          object
 90   HVC+                                    object
 91   HVB+                                    object
 92   CORIONICBIOPSY                          object
 93   Cordocentesis                           float64
 94   Cannabis                                object
 95   COCCAINE                                object
 96   Heroin                                  object
 97   others                                  object
 98   IUGR                                    object
 99   Colestasis                              object
 100  Diabetes                                object
 101  ABNORMALDOPPLER                         object
 102  ExitusFetal                             object
 103  STAINEDAMNIOTICLIQUID                   object
 104  NONCONFIDENTNST                         object
 105  Oligoamnios                             object
 106  MATERNALDISEASE                         object
 107  SGD                                     object
 108  Preeclampsia                            object
 109  PROM.1                                  object
 110  INITIALPROLONGEDPREGNANCY               object
 111  OTHERS                                  object
 112  LOC                                     object
 113  REG                                     object
 114  GEN                                     object
 115  UTERINEATONY                            object
 116  AMNIOTICLIQUIDEMBOLISM                  float64
 117  PERINEALHEMATOMA                        object
 118  UTERINEHAEMORRAGE                       object
 119  INVERTEDUTERUS                          object
 120  MATERNALDEATH                           object
 121  RETAINEDPLACENTA                        object
 122  UTERINERUPTURE                          object
 123  PULMONARTHROMBOEMBOLISM                 object
 124  DEEPVENOUSTHROMBOSIS                    object
 125  SHOULDERDYSTOCIA                        object
 126  TEARREPAIR                              object
 127  MANUALEXTRACTIONOFPLACENTA              object
 128  HISTERECTOMY                            object
 129  POSTPARTUMCURETAGE                      object
 130  REPOSITIONOFINVERTEDUTERUS              object
 131  BLOODTRANSFUSION                        object
 132  MEDICALTREATMENT                        object
 133  MANUALASSITANCETOSHOULDERDYSTOCIA       object
 134  ARTHERIALEMBOLIZATION                   object
 135  HEMATOMALDRAINAGE                       object
 136  INTRAPARTUMpHvalue                      object
 137  sexfetus1                               object
 138  weightfetus1                            object
 139  apgarfetus1                             object
 140  apgarfetus1fivemin                      object
 141  pHvaluefetus1umbilicalarthery           object
 142  FETUS1ADMISSIONICU                      object
 143  FETUS1RECOVERY                          object
 144  FETUS1MECONIUMASPIRATIONSYNDROME        object
dtypes: float64(7), int64(8), object(130)
memory usage: 6.8+ MB

### Checking missing values

In [ ]:
c_df.isnull().sum()

AGE                                    0
COUPLESITUATION                        0
HEIGHT                                 0
WEIGHT                                 0
BMI                                    0
                                    ...
apgarfetus1fivemin                  4219
pHvaluefetus1umbilicalarthery          0
FETUS1ADMISSIONICU                  4238
FETUS1RECOVERY                      4235
FETUS1MECONIUMASPIRATIONSYNDROME    4234
Length: 145, dtype: int64

### Class labels

In [ ]:
c_df.TYPEOFBIRTH.unique()

array(['emergencyc-section', 'CESprogrammed', 'EUT', 'vacum', 'FORC',
       'ESP', 'NALGASVAGINAL'], dtype=object)

In [ ]:
a = c_df['TYPEOFBIRTH'].values.tolist()
s = set(a)
for x in s:
  print(x,":",a.count(x))

EUT : 4231
emergencyc-section : 692
vacum : 770
CESprogrammed : 325
ESP : 44
FORC : 87
NALGASVAGINAL : 8

### Preprocessing

### Dataset after feature extraction

In [ ]:
hm_df = c_df[['PREVIOUSCESAREAN','COMPLICATIONS','ROBSONGROUP','ARTMODE','PREVIOUSPRETERMPREGNANCIES','AMNIOCENTESIS','PREINDUCTION','INDUCTION',
        'EPISIOTOMY','OXYTOCIN','FetalINTRAPARTUMpH','PARITY','OBSTETRICRISK','COMORBIDITY','NUMBEROFPREVCESAREAN','KGINCREASEDPREGNANCY','STARTANTENATALCARRE',
        'ART','PREVIOUSTERMPREGNANCIES','AMNIOTICLIQUID','MISCARRIAGES','ANESTHESIA','TYPEOFBIRTH']]

### Checking duplicates

In [ ]:
hm_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
6152    False
6153     True
6154    False
6155    False
6156     True
Length: 6157, dtype: bool

In [ ]:
hm_df.duplicated().sum()

896

### Drop duplicate records

In [ ]:
hm_df = hm_df.drop_duplicates()
hm_df

,PREVIOUSCESAREAN,COMPLICATIONS,ROBSONGROUP,ARTMODE,PREVIOUSPRETERMPREGNANCIES,AMNIOCENTESIS,PREINDUCTION,INDUCTION,EPISIOTOMY,OXYTOCIN,...,COMORBIDITY,NUMBEROFPREVCESAREAN,KGINCREASEDPREGNANCY,STARTANTENATALCARRE,ART,PREVIOUSTERMPREGNANCIES,AMNIOTICLIQUID,MISCARRIAGES,ANESTHESIA,TYPEOFBIRTH
0,f,f,group2a,NaN,0,f,t,t,NaN,t,...,f,NaN,14,1ºtrimester,f,0,stained+,0,t,emergencyc-section
1,f,f,group6,NaN,0,f,f,f,NaN,f,...,f,NaN,5,1ºtrimester,f,0,clear,1,t,CESprogrammed
2,f,f,group1,NaN,0,f,f,f,f,t,...,f,NaN,12,1ºtrimester,f,0,clear,1,t,EUT
3,t,f,group5,NaN,0,f,f,f,f,f,...,f,1.0,12,1ºtrimester,f,1,stained+,0,t,EUT
4,f,f,group1,FIV,0,f,f,f,f,t,...,f,NaN,11,1ºtrimester,t,0,clear,1,t,EUT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6150,f,f,group1,NaN,0,f,f,f,f,t,...,f,0.0,0,1ºtrimester,f,0,stained+,0,t,emergencyc-section
6151,f,f,group2a,NaN,0,f,f,t,f,f,...,f,0.0,0,2ºtrimester,f,0,stained+,0,t,emergencyc-section
6152,f,f,group8,NaN,0,t,f,f,t,f,...,t,0.0,13,1ºtrimester,f,0,clear,0,t,EUT
6154,f,f,group1,IAD,0,f,f,f,f,f,...,f,0.0,0,1ºtrimester,t,0,clear,2,t,EUT
6155,f,f,group2a,FIV,0,f,f,t,f,t,...,f,0.0,3,1ºtrimester,t,1,clear,2,t,emergencyc-section

In [ ]:
import numpy as np
hm_df = hm_df.replace(r'^\s*$', np.nan, regex=True)

### Handling missing values of categorical attributes by mode

In [ ]:
s = (hm_df.dtypes == 'object')
#print(s)
#print(s[s])
object_cols = list(s[s].index)
print("Categorical variables:")
print(object_cols)
print(len(object_cols))

Categorical variables:
['PREVIOUSCESAREAN', 'COMPLICATIONS', 'ROBSONGROUP', 'ARTMODE', 'AMNIOCENTESIS', 'PREINDUCTION', 'INDUCTION', 'EPISIOTOMY', 'OXYTOCIN', 'FetalINTRAPARTUMpH', 'OBSTETRICRISK', 'COMORBIDITY', 'STARTANTENATALCARRE', 'ART', 'AMNIOTICLIQUID', 'ANESTHESIA', 'TYPEOFBIRTH']
17

In [ ]:
for i in object_cols:
  x = hm_df[i].mode()[0]
  hm_df[i].fillna(x,inplace = True)
hm_df

,PREVIOUSCESAREAN,COMPLICATIONS,ROBSONGROUP,ARTMODE,PREVIOUSPRETERMPREGNANCIES,AMNIOCENTESIS,PREINDUCTION,INDUCTION,EPISIOTOMY,OXYTOCIN,...,COMORBIDITY,NUMBEROFPREVCESAREAN,KGINCREASEDPREGNANCY,STARTANTENATALCARRE,ART,PREVIOUSTERMPREGNANCIES,AMNIOTICLIQUID,MISCARRIAGES,ANESTHESIA,TYPEOFBIRTH
0,f,f,group2a,FIV,0,f,t,t,f,t,...,f,NaN,14,1ºtrimester,f,0,stained+,0,t,emergencyc-section
1,f,f,group6,FIV,0,f,f,f,f,f,...,f,NaN,5,1ºtrimester,f,0,clear,1,t,CESprogrammed
2,f,f,group1,FIV,0,f,f,f,f,t,...,f,NaN,12,1ºtrimester,f,0,clear,1,t,EUT
3,t,f,group5,FIV,0,f,f,f,f,f,...,f,1.0,12,1ºtrimester,f,1,stained+,0,t,EUT
4,f,f,group1,FIV,0,f,f,f,f,t,...,f,NaN,11,1ºtrimester,t,0,clear,1,t,EUT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6150,f,f,group1,FIV,0,f,f,f,f,t,...,f,0.0,0,1ºtrimester,f,0,stained+,0,t,emergencyc-section
6151,f,f,group2a,FIV,0,f,f,t,f,f,...,f,0.0,0,2ºtrimester,f,0,stained+,0,t,emergencyc-section
6152,f,f,group8,FIV,0,t,f,f,t,f,...,t,0.0,13,1ºtrimester,f,0,clear,0,t,EUT
6154,f,f,group1,IAD,0,f,f,f,f,f,...,f,0.0,0,1ºtrimester,t,0,clear,2,t,EUT
6155,f,f,group2a,FIV,0,f,f,t,f,t,...,f,0.0,3,1ºtrimester,t,1,clear,2,t,emergencyc-section

### Handling missing values of Numerical attributes using mean

In [ ]:
s = (hm_df.dtypes != 'object')
number_cols = list(s[s].index)
print("Numerical variables:")
print(number_cols)
print(len(number_cols))

Numerical variables:
['PREVIOUSPRETERMPREGNANCIES', 'PARITY', 'NUMBEROFPREVCESAREAN', 'KGINCREASEDPREGNANCY', 'PREVIOUSTERMPREGNANCIES', 'MISCARRIAGES']
6

In [ ]:
for i in number_cols:
  x = hm_df[i].mean()
  hm_df[i].fillna(x,inplace = True)
hm_df

,PREVIOUSCESAREAN,COMPLICATIONS,ROBSONGROUP,ARTMODE,PREVIOUSPRETERMPREGNANCIES,AMNIOCENTESIS,PREINDUCTION,INDUCTION,EPISIOTOMY,OXYTOCIN,...,COMORBIDITY,NUMBEROFPREVCESAREAN,KGINCREASEDPREGNANCY,STARTANTENATALCARRE,ART,PREVIOUSTERMPREGNANCIES,AMNIOTICLIQUID,MISCARRIAGES,ANESTHESIA,TYPEOFBIRTH
0,f,f,group2a,FIV,0,f,t,t,f,t,...,f,0.560456,14,1ºtrimester,f,0,stained+,0,t,emergencyc-section
1,f,f,group6,FIV,0,f,f,f,f,f,...,f,0.560456,5,1ºtrimester,f,0,clear,1,t,CESprogrammed
2,f,f,group1,FIV,0,f,f,f,f,t,...,f,0.560456,12,1ºtrimester,f,0,clear,1,t,EUT
3,t,f,group5,FIV,0,f,f,f,f,f,...,f,1.000000,12,1ºtrimester,f,1,stained+,0,t,EUT
4,f,f,group1,FIV,0,f,f,f,f,t,...,f,0.560456,11,1ºtrimester,t,0,clear,1,t,EUT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6150,f,f,group1,FIV,0,f,f,f,f,t,...,f,0.000000,0,1ºtrimester,f,0,stained+,0,t,emergencyc-section
6151,f,f,group2a,FIV,0,f,f,t,f,f,...,f,0.000000,0,2ºtrimester,f,0,stained+,0,t,emergencyc-section
6152,f,f,group8,FIV,0,t,f,f,t,f,...,t,0.000000,13,1ºtrimester,f,0,clear,0,t,EUT
6154,f,f,group1,IAD,0,f,f,f,f,f,...,f,0.000000,0,1ºtrimester,t,0,clear,2,t,EUT
6155,f,f,group2a,FIV,0,f,f,t,f,t,...,f,0.000000,3,1ºtrimester,t,1,clear,2,t,emergencyc-section

In [ ]:
hm_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5261 entries, 0 to 6155
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PREVIOUSCESAREAN            5261 non-null   object
 1   COMPLICATIONS               5261 non-null   object
 2   ROBSONGROUP                 5261 non-null   object
 3   ARTMODE                     5261 non-null   object
 4   PREVIOUSPRETERMPREGNANCIES  5261 non-null   int64
 5   AMNIOCENTESIS               5261 non-null   object
 6   PREINDUCTION                5261 non-null   object
 7   INDUCTION                   5261 non-null   object
 8   EPISIOTOMY                  5261 non-null   object
 9   OXYTOCIN                    5261 non-null   object
 10  FetalINTRAPARTUMpH          5261 non-null   object
 11  PARITY                      5261 non-null   int64
 12  OBSTETRICRISK               5261 non-null   object
 13  COMORBIDITY                 5261 non-null   object
 14  NUMBEROFPREVCESAREAN        5261 non-null   float64
 15  KGINCREASEDPREGNANCY        5261 non-null   int64
 16  STARTANTENATALCARRE         5261 non-null   object
 17  ART                         5261 non-null   object
 18  PREVIOUSTERMPREGNANCIES     5261 non-null   int64
 19  AMNIOTICLIQUID              5261 non-null   object
 20  MISCARRIAGES                5261 non-null   int64
 21  ANESTHESIA                  5261 non-null   object
 22  TYPEOFBIRTH                 5261 non-null   object
dtypes: float64(1), int64(5), object(17)
memory usage: 986.4+ KB

### Checking NULL values

In [ ]:
hm_df.isnull().sum()

PREVIOUSCESAREAN              0
COMPLICATIONS                 0
ROBSONGROUP                   0
ARTMODE                       0
PREVIOUSPRETERMPREGNANCIES    0
AMNIOCENTESIS                 0
PREINDUCTION                  0
INDUCTION                     0
EPISIOTOMY                    0
OXYTOCIN                      0
FetalINTRAPARTUMpH            0
PARITY                        0
OBSTETRICRISK                 0
COMORBIDITY                   0
NUMBEROFPREVCESAREAN          0
KGINCREASEDPREGNANCY          0
STARTANTENATALCARRE           0
ART                           0
PREVIOUSTERMPREGNANCIES       0
AMNIOTICLIQUID                0
MISCARRIAGES                  0
ANESTHESIA                    0
TYPEOFBIRTH                   0
dtype: int64

In [ ]:
hm_df.TYPEOFBIRTH.unique()

array(['emergencyc-section', 'CESprogrammed', 'EUT', 'vacum', 'FORC',
       'ESP', 'NALGASVAGINAL'], dtype=object)

In [ ]:
a = hm_df['TYPEOFBIRTH'].values.tolist()
s = set(a)
for x in s:
  print(x,":",a.count(x))

EUT : 3431
emergencyc-section : 667
vacum : 722
CESprogrammed : 302
ESP : 44
FORC : 87
NALGASVAGINAL : 8

In [ ]:
hm_df

,PREVIOUSCESAREAN,COMPLICATIONS,ROBSONGROUP,ARTMODE,PREVIOUSPRETERMPREGNANCIES,AMNIOCENTESIS,PREINDUCTION,INDUCTION,EPISIOTOMY,OXYTOCIN,...,COMORBIDITY,NUMBEROFPREVCESAREAN,KGINCREASEDPREGNANCY,STARTANTENATALCARRE,ART,PREVIOUSTERMPREGNANCIES,AMNIOTICLIQUID,MISCARRIAGES,ANESTHESIA,TYPEOFBIRTH
0,f,f,group2a,FIV,0,f,t,t,f,t,...,f,0.560456,14,1ºtrimester,f,0,stained+,0,t,emergencyc-section
1,f,f,group6,FIV,0,f,f,f,f,f,...,f,0.560456,5,1ºtrimester,f,0,clear,1,t,CESprogrammed
2,f,f,group1,FIV,0,f,f,f,f,t,...,f,0.560456,12,1ºtrimester,f,0,clear,1,t,EUT
3,t,f,group5,FIV,0,f,f,f,f,f,...,f,1.000000,12,1ºtrimester,f,1,stained+,0,t,EUT
4,f,f,group1,FIV,0,f,f,f,f,t,...,f,0.560456,11,1ºtrimester,t,0,clear,1,t,EUT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6150,f,f,group1,FIV,0,f,f,f,f,t,...,f,0.000000,0,1ºtrimester,f,0,stained+,0,t,emergencyc-section
6151,f,f,group2a,FIV,0,f,f,t,f,f,...,f,0.000000,0,2ºtrimester,f,0,stained+,0,t,emergencyc-section
6152,f,f,group8,FIV,0,t,f,f,t,f,...,t,0.000000,13,1ºtrimester,f,0,clear,0,t,EUT
6154,f,f,group1,IAD,0,f,f,f,f,f,...,f,0.000000,0,1ºtrimester,t,0,clear,2,t,EUT
6155,f,f,group2a,FIV,0,f,f,t,f,t,...,f,0.000000,3,1ºtrimester,t,1,clear,2,t,emergencyc-section

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

#hm_df.Publisher = hm_df.Publisher.astype(str)

for column in hm_df.columns:
    temp_new = le.fit_transform(hm_df[column].astype('category'))
    hm_df.drop(labels=[column], axis="columns", inplace=True)
    hm_df[column] = temp_new

X = hm_df.loc[:,'PREVIOUSCESAREAN':'ANESTHESIA']
Y = hm_df.loc[:,'TYPEOFBIRTH':]

In [ ]:
from imblearn.over_sampling import ADASYN 
sm = ADASYN(sampling_strategy='auto', random_state=None, n_neighbors=5, n_jobs=1)
X_adassin_1, Y_adassin_1 = sm.fit_resample(X, Y)
print(X_adassin_1.shape)
print(Y_adassin_1.shape)

(23785, 22)
(23785, 1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_adassin_1,Y_adassin_1,test_size=0.2,random_state=None)

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19028 entries, 10819 to 5480
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PREVIOUSCESAREAN            19028 non-null  int64
 1   COMPLICATIONS               19028 non-null  int64
 2   ROBSONGROUP                 19028 non-null  int64
 3   ARTMODE                     19028 non-null  int64
 4   PREVIOUSPRETERMPREGNANCIES  19028 non-null  int64
 5   AMNIOCENTESIS               19028 non-null  int64
 6   PREINDUCTION                19028 non-null  int64
 7   INDUCTION                   19028 non-null  int64
 8   EPISIOTOMY                  19028 non-null  int64
 9   OXYTOCIN                    19028 non-null  int64
 10  FetalINTRAPARTUMpH          19028 non-null  int64
 11  PARITY                      19028 non-null  int64
 12  OBSTETRICRISK               19028 non-null  int64
 13  COMORBIDITY                 19028 non-null  int64
 14  NUMBEROFPREVCESAREAN        19028 non-null  int64
 15  KGINCREASEDPREGNANCY        19028 non-null  int64
 16  STARTANTENATALCARRE         19028 non-null  int64
 17  ART                         19028 non-null  int64
 18  PREVIOUSTERMPREGNANCIES     19028 non-null  int64
 19  AMNIOTICLIQUID              19028 non-null  int64
 20  MISCARRIAGES                19028 non-null  int64
 21  ANESTHESIA                  19028 non-null  int64
dtypes: int64(22)
memory usage: 3.3 MB

In [ ]:
Y_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19028 entries, 10819 to 5480
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TYPEOFBIRTH  19028 non-null  int64
dtypes: int64(1)
memory usage: 297.3 KB

In [ ]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4757 entries, 15541 to 13846
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PREVIOUSCESAREAN            4757 non-null   int64
 1   COMPLICATIONS               4757 non-null   int64
 2   ROBSONGROUP                 4757 non-null   int64
 3   ARTMODE                     4757 non-null   int64
 4   PREVIOUSPRETERMPREGNANCIES  4757 non-null   int64
 5   AMNIOCENTESIS               4757 non-null   int64
 6   PREINDUCTION                4757 non-null   int64
 7   INDUCTION                   4757 non-null   int64
 8   EPISIOTOMY                  4757 non-null   int64
 9   OXYTOCIN                    4757 non-null   int64
 10  FetalINTRAPARTUMpH          4757 non-null   int64
 11  PARITY                      4757 non-null   int64
 12  OBSTETRICRISK               4757 non-null   int64
 13  COMORBIDITY                 4757 non-null   int64
 14  NUMBEROFPREVCESAREAN        4757 non-null   int64
 15  KGINCREASEDPREGNANCY        4757 non-null   int64
 16  STARTANTENATALCARRE         4757 non-null   int64
 17  ART                         4757 non-null   int64
 18  PREVIOUSTERMPREGNANCIES     4757 non-null   int64
 19  AMNIOTICLIQUID              4757 non-null   int64
 20  MISCARRIAGES                4757 non-null   int64
 21  ANESTHESIA                  4757 non-null   int64
dtypes: int64(22)
memory usage: 854.8 KB

In [ ]:
Y_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4757 entries, 15541 to 13846
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TYPEOFBIRTH  4757 non-null   int64
dtypes: int64(1)
memory usage: 74.3 KB

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
model = DecisionTreeClassifier(criterion = 'entropy')
model.fit(X_train,Y_train)
y_pred = model.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

0.8368719781374816
0.8326670529429883
0.8368719781374816
0.8368719781374816

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier()
RFC.fit(X_train, Y_train.values.ravel())
y_pred = RFC.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

0.8673533739751944
0.8662307069774228
0.8673533739751944
0.8673533739751944

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
svc = SVC(gamma = 0.001, C = 1000)
y_pred = svc.fit(X_train, Y_train.values.ravel()).predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

0.751944502837923
0.7559471125111631
0.751944502837923
0.7519445028379231

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
K = []
training = []
test = []
scores = {}
  
for k in range(2, 21):
    clf = KNeighborsClassifier(n_neighbors = k)
    clf.fit(X_train, Y_train.values.ravel())
  
    training_score = clf.score(X_train, Y_train)
    test_score = clf.score(X_test, Y_test)
    K.append(k)
  
    training.append(training_score)
    test.append(test_score)
    scores[k] = [training_score, test_score]
for keys, values in scores.items():
    print(keys, ':', values)

2 : [0.8990960689510196, 0.8129072945133488]
3 : [0.8933676686987597, 0.8215261719571159]
4 : [0.871505150304814, 0.8095438301450494]
5 : [0.8633067059070842, 0.8118562118982552]
6 : [0.8515871347487912, 0.7981921379020391]
7 : [0.8437040151355897, 0.7935673743956275]
8 : [0.8367143157452176, 0.7866302291360101]
9 : [0.8270969098171116, 0.7782215682152617]
10 : [0.8211057389110784, 0.7756989699390372]
11 : [0.8149043514820264, 0.7710742064326256]
12 : [0.8087029640529746, 0.7626655455118773]
13 : [0.8017132646626025, 0.7590918646205592]
14 : [0.7956695396258145, 0.7525751524069791]
15 : [0.7898360311120454, 0.7494219045616985]
16 : [0.7856842547824259, 0.7458482236703805]
17 : [0.7811120454067689, 0.7412234601639689]
18 : [0.7755413075467732, 0.7359680470885012]
19 : [0.7703384486020601, 0.7357578305654825]
20 : [0.7672377548875342, 0.7309228505360521]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=2,weights='distance',p=1)
model.fit(X_train,Y_train.values.ravel())
y_pred = model.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

0.8393945764137061
0.8366483189048428
0.8393945764137061
0.8393945764137062

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import StackingClassifier
estimators = [('rf', RandomForestClassifier()),('svr', make_pipeline(StandardScaler(),LinearSVC())),('dt',DecisionTreeClassifier(criterion = 'entropy')),('knn',KNeighborsClassifier(n_neighbors=2,weights='distance',p=1))]
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
clf.fit(X_train, Y_train.values.ravel())
y_pred = clf.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

0.8738700861887745
0.8723145213122198
0.8738700861887745
0.8738700861887745

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,