In [ ]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

### Read the datasets

In [ ]:
import pandas
ha_df = pandas.read_csv("/content/drive/My Drive/datasets/ha.csv")
hb_df = pandas.read_csv("/content/drive/My Drive/datasets/hb.csv")
hc_df = pandas.read_csv("/content/drive/My Drive/datasets/hc.csv")
hd_df = pandas.read_csv("/content/drive/My Drive/datasets/hd.csv")

In [ ]:
ha_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1923 entries, 0 to 1922
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(13), int64(8), object(124)
memory usage: 2.1+ MB

In [ ]:
hb_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(38), int64(9), object(98)
memory usage: 1011.7+ KB

In [ ]:
hc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2458 entries, 0 to 2457
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(22), int64(9), object(114)
memory usage: 2.7+ MB

In [ ]:
hd_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 883 entries, 0 to 882
Columns: 145 entries, AGE to FETUS1MECONIUMASPIRATIONSYNDROME
dtypes: float64(42), int64(13), object(90)
memory usage: 1000.4+ KB

### Concatenating the datasets

In [ ]:
c_df = pandas.concat([ha_df, hb_df, hc_df, hd_df], ignore_index=True)
c_df

,AGE,COUPLESITUATION,HEIGHT,WEIGHT,BMI,COUNTRYOFORIGYN,MATERNALEDUCATION,STARTANTENATALCARRE,SUBSTANCEABUSE,SMOKING,...,HEMATOMALDRAINAGE,INTRAPARTUMpHvalue,sexfetus1,weightfetus1,apgarfetus1,apgarfetus1fivemin,pHvaluefetus1umbilicalarthery,FETUS1ADMISSIONICU,FETUS1RECOVERY,FETUS1MECONIUMASPIRATIONSYNDROME
0,30,withcouple,1.58,70.0,28.04,CHILE,secondary,1ºtrimester,f,f,...,NaN,NaN,Masculino,2640,7,9,7.34,f,1:Aspiraciónnasofaríngea,f
1,38,withcouple,1.61,79.0,30.48,ESPAÑA,secondary,1ºtrimester,f,f,...,NaN,NaN,Femenino,3040,8,9,7.26,f,0:noprecisa,f
2,25,withcouple,1.56,72.0,29.59,COLOMBIA,secondary,1ºtrimester,f,f,...,NaN,NaN,Femenino,3820,10,10,7.21,f,0:noprecisa,f
3,31,withcouple,1.62,54.0,20.58,ESPAÑA,secondary,1ºtrimester,f,f,...,NaN,NaN,Femenino,3390,9,10,7.21,f,0:noprecisa,f
4,28,withcouple,1.47,51.0,23.60,ESPAÑA,secondary,1ºtrimester,f,f,...,NaN,NaN,Masculino,3020,8,9,7.17,f,0:noprecisa,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6152,35,withcouple,1.56,49.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,1960,10,10,7.27,f,NaN,f,NaN,NaN,NaN
6153,29,withcouple,1.64,59.0,21.51,ESPAÑA,secondary,1ºtrimester,f,f,...,3310,9,10,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN
6154,39,withcouple,1.59,64.0,20.00,ESPAÑA,secondary,1ºtrimester,f,f,...,3830,8,9,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN
6155,41,withcouple,1.48,50.0,23.28,ESPAÑA,primary,1ºtrimester,f,f,...,2810,10,10,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN
6156,32,withcouple,1.65,75.2,24.00,ARGELIA,Sinestudios,1ºtrimester,f,f,...,3160,10,10,DESCONOCIDO,f,NaN,f,NaN,NaN,NaN

### Information of the concatenated dataset

In [ ]:
c_df.info(145)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6157 entries, 0 to 6156
Data columns (total 145 columns):
 #    Column                                  Dtype
---   ------                                  -----
 0    AGE                                     int64
 1    COUPLESITUATION                         object
 2    HEIGHT                                  float64
 3    WEIGHT                                  float64
 4    BMI                                     float64
 5    COUNTRYOFORIGYN                         object
 6    MATERNALEDUCATION                       object
 7    STARTANTENATALCARRE                     object
 8    SUBSTANCEABUSE                          object
 9    SMOKING                                 object
 10   CIGARRETTESPERDAY                       float64
 11   ALCOHOL                                 object
 12   DAILYALCOHOLINTAKE                      object
 13   KGINCREASEDPREGNANCY                    int64
 14   ART                                     object
 15   ARTMODE                                 object
 16   AMNIOCENTESIS                           object
 17   PREVIOUSCESAREAN                        object
 18   NUMBEROFPREVCESAREAN                    float64
 19   COMORBIDITY                             object
 20   OBSTETRICRISK                           object
 21   PREVIOUSTERMPREGNANCIES                 int64
 22   PREVIOUSPRETERMPREGNANCIES              int64
 23   MISCARRIAGES                            int64
 24   ALIVENEWBORNS                           int64
 25   PARITY                                  int64
 26   PREINDUCTION                            object
 27   INDUCTION                               object
 28   HOURSROMBEFOREINDUCTION                 object
 29   ANESTHESIA                              object
 30   HOURSOFRUPTUREDMEMBRANESATDELIVERY      object
 31   GESTAGIONALAGE                          int64
 32   CARDIOTOCOGRAPHY                        object
 33   TYPEOFBIRTH                             object
 34   EPISIOTOMY                              object
 35   TEAR                                    object
 36   MEDICALINDICATION                       object
 37   EMERGENCYCESAREANSECTION                object
 38   PROGRAMMEDCESAREANSECTION               object
 39   OXYTOCIN                                object
 40   AMNIOTICLIQUID                          object
 41   FetalINTRAPARTUMpH                      object
 42   COMPLICATIONS                           object
 43   ROBSONGROUP                             object
 44   CESAREANINACCORDANCETOCLINICALSTANDARD  object
 45   COLESTASISGRAVIDICA                     object
 46   CORIONAMNIONITIS                        object
 47   NONIDGESTATIONALDIABETES                object
 48   IDGESTATIONALDIABETES                   object
 49   PROLONGEDPREGNANACY                     object
 50   MULTIPLEGESTATION                       object
 51   HELLP                                   object
 52   GESTATIONALHYPERTENSION                 object
 53   ISOINMUNIZACION                         object
 54   STAINEDAMNIOTICLIQUOR                   object
 55   FETALMALFORMATION                       object
 56   UTERINEMALFORMATION                     object
 57   FETALMALPOSITION                        object
 58   MIOMECTOMY                              object
 59   OLIGOAMNIOS                             object
 60   PREVIOUSPRETERMDELIVERY                 object
 61   PLACENTAPREVIA                          object
 62   POLIHIDRAMNIOS                          object
 63   SEVEREPREECLAMPSIA                      object
 64   MILDPREECLAMPSIA                        object
 65   PROM                                    object
 66   SIFILIS                                 object
 67   TOXOPLASMOSIS                           object
 68   REPEATEDMISCARRIAGES                    object
 69   PREVIOUSFETALLOSSES                     object
 70   ANTEPARTUMLOSSOFFETALWELLBEEING         object
 71   MATERNALANEMIA                          object
 72   ASTHMA                                  object
 73   CARDIACDISEASE                          object
 74   Coagulopathy                            object
 75   PREGESTATIONALTYPEIDIABETES             object
 76   PREGESTATIONALTYPEIIDIABETES            object
 77   AUTOINMUNEDISEASEINTREATMENT            object
 78   EPILEPSYINTREATMENT                     object
 79   MENTALDISEASEINTREATMENT                object
 80   NEUROLOGICALDISEASEINTREATMENT          object
 81   RENALDISEASEINTREATMENT                 object
 82   Hemiplegia                              object
 83   LIVERDISEASEINTREATMENT                 object
 84   HIPERTHYROIDISMINTREATMENT              object
 85   HIPOTHYROIDISMINTREATMENT               object
 86   HIV+                                    object
 87   CHRONICHYPERTENSION                     object
 88   TIP                                     object
 89   MALIGNANTTUMOR                          object
 90   HVC+                                    object
 91   HVB+                                    object
 92   CORIONICBIOPSY                          object
 93   Cordocentesis                           float64
 94   Cannabis                                object
 95   COCCAINE                                object
 96   Heroin                                  object
 97   others                                  object
 98   IUGR                                    object
 99   Colestasis                              object
 100  Diabetes                                object
 101  ABNORMALDOPPLER                         object
 102  ExitusFetal                             object
 103  STAINEDAMNIOTICLIQUID                   object
 104  NONCONFIDENTNST                         object
 105  Oligoamnios                             object
 106  MATERNALDISEASE                         object
 107  SGD                                     object
 108  Preeclampsia                            object
 109  PROM.1                                  object
 110  INITIALPROLONGEDPREGNANCY               object
 111  OTHERS                                  object
 112  LOC                                     object
 113  REG                                     object
 114  GEN                                     object
 115  UTERINEATONY                            object
 116  AMNIOTICLIQUIDEMBOLISM                  float64
 117  PERINEALHEMATOMA                        object
 118  UTERINEHAEMORRAGE                       object
 119  INVERTEDUTERUS                          object
 120  MATERNALDEATH                           object
 121  RETAINEDPLACENTA                        object
 122  UTERINERUPTURE                          object
 123  PULMONARTHROMBOEMBOLISM                 object
 124  DEEPVENOUSTHROMBOSIS                    object
 125  SHOULDERDYSTOCIA                        object
 126  TEARREPAIR                              object
 127  MANUALEXTRACTIONOFPLACENTA              object
 128  HISTERECTOMY                            object
 129  POSTPARTUMCURETAGE                      object
 130  REPOSITIONOFINVERTEDUTERUS              object
 131  BLOODTRANSFUSION                        object
 132  MEDICALTREATMENT                        object
 133  MANUALASSITANCETOSHOULDERDYSTOCIA       object
 134  ARTHERIALEMBOLIZATION                   object
 135  HEMATOMALDRAINAGE                       object
 136  INTRAPARTUMpHvalue                      object
 137  sexfetus1                               object
 138  weightfetus1                            object
 139  apgarfetus1                             object
 140  apgarfetus1fivemin                      object
 141  pHvaluefetus1umbilicalarthery           object
 142  FETUS1ADMISSIONICU                      object
 143  FETUS1RECOVERY                          object
 144  FETUS1MECONIUMASPIRATIONSYNDROME        object
dtypes: float64(7), int64(8), object(130)
memory usage: 6.8+ MB

### Checking missing values

In [ ]:
c_df.isnull().sum()

AGE                                    0
COUPLESITUATION                        0
HEIGHT                                 0
WEIGHT                                 0
BMI                                    0
                                    ...
apgarfetus1fivemin                  4219
pHvaluefetus1umbilicalarthery          0
FETUS1ADMISSIONICU                  4238
FETUS1RECOVERY                      4235
FETUS1MECONIUMASPIRATIONSYNDROME    4234
Length: 145, dtype: int64

### Class labels

In [ ]:
c_df.TYPEOFBIRTH.unique()

array(['emergencyc-section', 'CESprogrammed', 'EUT', 'vacum', 'FORC',
       'ESP', 'NALGASVAGINAL'], dtype=object)

In [ ]:
a = c_df['TYPEOFBIRTH'].values.tolist()
s = set(a)
for x in s:
  print(x,":",a.count(x))

emergencyc-section : 692
CESprogrammed : 325
vacum : 770
EUT : 4231
NALGASVAGINAL : 8
ESP : 44
FORC : 87

### Preprocessing

### Dataset after feature extraction

In [ ]:
ml_df = c_df[['PARITY','OBSTETRICRISK','COMORBIDITY','NUMBEROFPREVCESAREAN','KGINCREASEDPREGNANCY','STARTANTENATALCARRE',
        'ART','PREVIOUSTERMPREGNANCIES','AMNIOTICLIQUID','MISCARRIAGES','ANESTHESIA',
        'GESTAGIONALAGE','HEIGHT','WEIGHT','BMI','AGE','CARDIOTOCOGRAPHY','MATERNALEDUCATION','SUBSTANCEABUSE','SMOKING','ALCOHOL','TYPEOFBIRTH']]

### Checking duplicates

In [ ]:
ml_df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
6152    False
6153    False
6154    False
6155    False
6156    False
Length: 6157, dtype: bool

In [ ]:
ml_df.duplicated().sum()

20

### Drop duplicate records

In [ ]:
ml_df = ml_df.drop_duplicates()
ml_df

,PARITY,OBSTETRICRISK,COMORBIDITY,NUMBEROFPREVCESAREAN,KGINCREASEDPREGNANCY,STARTANTENATALCARRE,ART,PREVIOUSTERMPREGNANCIES,AMNIOTICLIQUID,MISCARRIAGES,...,HEIGHT,WEIGHT,BMI,AGE,CARDIOTOCOGRAPHY,MATERNALEDUCATION,SUBSTANCEABUSE,SMOKING,ALCOHOL,TYPEOFBIRTH
0,0,t,f,NaN,14,1ºtrimester,f,0,stained+,0,...,1.58,70.0,28.04,30,continuous,secondary,f,f,f,emergencyc-section
1,10,f,f,NaN,5,1ºtrimester,f,0,clear,1,...,1.61,79.0,30.48,38,continuous,secondary,f,f,f,CESprogrammed
2,10,f,f,NaN,12,1ºtrimester,f,0,clear,1,...,1.56,72.0,29.59,25,continuous,secondary,f,f,f,EUT
3,1001,t,f,1.0,12,1ºtrimester,f,1,stained+,0,...,1.62,54.0,20.58,31,continuous,secondary,f,f,f,EUT
4,10,f,f,NaN,11,1ºtrimester,t,0,clear,1,...,1.47,51.0,23.60,28,continuous,secondary,f,f,f,EUT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6152,0,t,t,0.0,13,1ºtrimester,f,0,clear,0,...,1.56,49.0,20.00,35,continuous,secondary,f,f,f,EUT
6153,1001,f,f,0.0,0,1ºtrimester,f,1,clear,0,...,1.64,59.0,21.51,29,continuous,secondary,f,f,f,EUT
6154,20,f,f,0.0,0,1ºtrimester,t,0,clear,2,...,1.59,64.0,20.00,39,discontinuous,secondary,f,f,t,EUT
6155,1020,t,f,0.0,3,1ºtrimester,t,1,clear,2,...,1.48,50.0,23.28,41,continuous,primary,f,f,f,emergencyc-section
6156,2002,f,f,0.0,0,1ºtrimester,f,2,clear,0,...,1.65,75.2,24.00,32,discontinuous,Sinestudios,f,f,f,EUT

In [ ]:
import numpy as np
ml_df = ml_df.replace(r'^\s*$', np.nan, regex=True)

### Handling missing values of categorical attributes by mode

In [ ]:
s = (ml_df.dtypes == 'object')
#print(s)
#print(s[s])
object_cols = list(s[s].index)
print("Categorical variables:")
print(object_cols)
print(len(object_cols))

Categorical variables:
['OBSTETRICRISK', 'COMORBIDITY', 'STARTANTENATALCARRE', 'ART', 'AMNIOTICLIQUID', 'ANESTHESIA', 'CARDIOTOCOGRAPHY', 'MATERNALEDUCATION', 'SUBSTANCEABUSE', 'SMOKING', 'ALCOHOL', 'TYPEOFBIRTH']
12

In [ ]:
for i in object_cols:
  x = ml_df[i].mode()[0]
  ml_df[i].fillna(x,inplace = True)
ml_df

,PARITY,OBSTETRICRISK,COMORBIDITY,NUMBEROFPREVCESAREAN,KGINCREASEDPREGNANCY,STARTANTENATALCARRE,ART,PREVIOUSTERMPREGNANCIES,AMNIOTICLIQUID,MISCARRIAGES,...,HEIGHT,WEIGHT,BMI,AGE,CARDIOTOCOGRAPHY,MATERNALEDUCATION,SUBSTANCEABUSE,SMOKING,ALCOHOL,TYPEOFBIRTH
0,0,t,f,NaN,14,1ºtrimester,f,0,stained+,0,...,1.58,70.0,28.04,30,continuous,secondary,f,f,f,emergencyc-section
1,10,f,f,NaN,5,1ºtrimester,f,0,clear,1,...,1.61,79.0,30.48,38,continuous,secondary,f,f,f,CESprogrammed
2,10,f,f,NaN,12,1ºtrimester,f,0,clear,1,...,1.56,72.0,29.59,25,continuous,secondary,f,f,f,EUT
3,1001,t,f,1.0,12,1ºtrimester,f,1,stained+,0,...,1.62,54.0,20.58,31,continuous,secondary,f,f,f,EUT
4,10,f,f,NaN,11,1ºtrimester,t,0,clear,1,...,1.47,51.0,23.60,28,continuous,secondary,f,f,f,EUT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6152,0,t,t,0.0,13,1ºtrimester,f,0,clear,0,...,1.56,49.0,20.00,35,continuous,secondary,f,f,f,EUT
6153,1001,f,f,0.0,0,1ºtrimester,f,1,clear,0,...,1.64,59.0,21.51,29,continuous,secondary,f,f,f,EUT
6154,20,f,f,0.0,0,1ºtrimester,t,0,clear,2,...,1.59,64.0,20.00,39,discontinuous,secondary,f,f,t,EUT
6155,1020,t,f,0.0,3,1ºtrimester,t,1,clear,2,...,1.48,50.0,23.28,41,continuous,primary,f,f,f,emergencyc-section
6156,2002,f,f,0.0,0,1ºtrimester,f,2,clear,0,...,1.65,75.2,24.00,32,discontinuous,Sinestudios,f,f,f,EUT

### Handling missing values of Numerical attributes using mean

In [ ]:
s = (ml_df.dtypes != 'object')
number_cols = list(s[s].index)
print("Numerical variables:")
print(number_cols)
print(len(number_cols))

Numerical variables:
['PARITY', 'NUMBEROFPREVCESAREAN', 'KGINCREASEDPREGNANCY', 'PREVIOUSTERMPREGNANCIES', 'MISCARRIAGES', 'GESTAGIONALAGE', 'HEIGHT', 'WEIGHT', 'BMI', 'AGE']
10

In [ ]:
for i in number_cols:
  x = ml_df[i].mean()
  ml_df[i].fillna(x,inplace = True)
ml_df

,PARITY,OBSTETRICRISK,COMORBIDITY,NUMBEROFPREVCESAREAN,KGINCREASEDPREGNANCY,STARTANTENATALCARRE,ART,PREVIOUSTERMPREGNANCIES,AMNIOTICLIQUID,MISCARRIAGES,...,HEIGHT,WEIGHT,BMI,AGE,CARDIOTOCOGRAPHY,MATERNALEDUCATION,SUBSTANCEABUSE,SMOKING,ALCOHOL,TYPEOFBIRTH
0,0,t,f,0.514344,14,1ºtrimester,f,0,stained+,0,...,1.58,70.0,28.04,30,continuous,secondary,f,f,f,emergencyc-section
1,10,f,f,0.514344,5,1ºtrimester,f,0,clear,1,...,1.61,79.0,30.48,38,continuous,secondary,f,f,f,CESprogrammed
2,10,f,f,0.514344,12,1ºtrimester,f,0,clear,1,...,1.56,72.0,29.59,25,continuous,secondary,f,f,f,EUT
3,1001,t,f,1.000000,12,1ºtrimester,f,1,stained+,0,...,1.62,54.0,20.58,31,continuous,secondary,f,f,f,EUT
4,10,f,f,0.514344,11,1ºtrimester,t,0,clear,1,...,1.47,51.0,23.60,28,continuous,secondary,f,f,f,EUT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6152,0,t,t,0.000000,13,1ºtrimester,f,0,clear,0,...,1.56,49.0,20.00,35,continuous,secondary,f,f,f,EUT
6153,1001,f,f,0.000000,0,1ºtrimester,f,1,clear,0,...,1.64,59.0,21.51,29,continuous,secondary,f,f,f,EUT
6154,20,f,f,0.000000,0,1ºtrimester,t,0,clear,2,...,1.59,64.0,20.00,39,discontinuous,secondary,f,f,t,EUT
6155,1020,t,f,0.000000,3,1ºtrimester,t,1,clear,2,...,1.48,50.0,23.28,41,continuous,primary,f,f,f,emergencyc-section
6156,2002,f,f,0.000000,0,1ºtrimester,f,2,clear,0,...,1.65,75.2,24.00,32,discontinuous,Sinestudios,f,f,f,EUT

In [ ]:
ml_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6137 entries, 0 to 6156
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PARITY                   6137 non-null   int64
 1   OBSTETRICRISK            6137 non-null   object
 2   COMORBIDITY              6137 non-null   object
 3   NUMBEROFPREVCESAREAN     6137 non-null   float64
 4   KGINCREASEDPREGNANCY     6137 non-null   int64
 5   STARTANTENATALCARRE      6137 non-null   object
 6   ART                      6137 non-null   object
 7   PREVIOUSTERMPREGNANCIES  6137 non-null   int64
 8   AMNIOTICLIQUID           6137 non-null   object
 9   MISCARRIAGES             6137 non-null   int64
 10  ANESTHESIA               6137 non-null   object
 11  GESTAGIONALAGE           6137 non-null   int64
 12  HEIGHT                   6137 non-null   float64
 13  WEIGHT                   6137 non-null   float64
 14  BMI                      6137 non-null   float64
 15  AGE                      6137 non-null   int64
 16  CARDIOTOCOGRAPHY         6137 non-null   object
 17  MATERNALEDUCATION        6137 non-null   object
 18  SUBSTANCEABUSE           6137 non-null   object
 19  SMOKING                  6137 non-null   object
 20  ALCOHOL                  6137 non-null   object
 21  TYPEOFBIRTH              6137 non-null   object
dtypes: float64(4), int64(6), object(12)
memory usage: 1.1+ MB

### Checking NULL values

In [ ]:
ml_df.isnull().sum()

PARITY                     0
OBSTETRICRISK              0
COMORBIDITY                0
NUMBEROFPREVCESAREAN       0
KGINCREASEDPREGNANCY       0
STARTANTENATALCARRE        0
ART                        0
PREVIOUSTERMPREGNANCIES    0
AMNIOTICLIQUID             0
MISCARRIAGES               0
ANESTHESIA                 0
GESTAGIONALAGE             0
HEIGHT                     0
WEIGHT                     0
BMI                        0
AGE                        0
CARDIOTOCOGRAPHY           0
MATERNALEDUCATION          0
SUBSTANCEABUSE             0
SMOKING                    0
ALCOHOL                    0
TYPEOFBIRTH                0
dtype: int64

In [ ]:
ml_df.TYPEOFBIRTH.unique()

array(['emergencyc-section', 'CESprogrammed', 'EUT', 'vacum', 'FORC',
       'ESP', 'NALGASVAGINAL'], dtype=object)

In [ ]:
a = ml_df['TYPEOFBIRTH'].values.tolist()
s = set(a)
for x in s:
  print(x,":",a.count(x))

emergencyc-section : 689
CESprogrammed : 325
vacum : 765
EUT : 4219
NALGASVAGINAL : 8
ESP : 44
FORC : 87

In [ ]:
ml_df

,PARITY,OBSTETRICRISK,COMORBIDITY,NUMBEROFPREVCESAREAN,KGINCREASEDPREGNANCY,STARTANTENATALCARRE,ART,PREVIOUSTERMPREGNANCIES,AMNIOTICLIQUID,MISCARRIAGES,...,HEIGHT,WEIGHT,BMI,AGE,CARDIOTOCOGRAPHY,MATERNALEDUCATION,SUBSTANCEABUSE,SMOKING,ALCOHOL,TYPEOFBIRTH
0,0,t,f,0.514344,14,1ºtrimester,f,0,stained+,0,...,1.58,70.0,28.04,30,continuous,secondary,f,f,f,emergencyc-section
1,10,f,f,0.514344,5,1ºtrimester,f,0,clear,1,...,1.61,79.0,30.48,38,continuous,secondary,f,f,f,CESprogrammed
2,10,f,f,0.514344,12,1ºtrimester,f,0,clear,1,...,1.56,72.0,29.59,25,continuous,secondary,f,f,f,EUT
3,1001,t,f,1.000000,12,1ºtrimester,f,1,stained+,0,...,1.62,54.0,20.58,31,continuous,secondary,f,f,f,EUT
4,10,f,f,0.514344,11,1ºtrimester,t,0,clear,1,...,1.47,51.0,23.60,28,continuous,secondary,f,f,f,EUT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6152,0,t,t,0.000000,13,1ºtrimester,f,0,clear,0,...,1.56,49.0,20.00,35,continuous,secondary,f,f,f,EUT
6153,1001,f,f,0.000000,0,1ºtrimester,f,1,clear,0,...,1.64,59.0,21.51,29,continuous,secondary,f,f,f,EUT
6154,20,f,f,0.000000,0,1ºtrimester,t,0,clear,2,...,1.59,64.0,20.00,39,discontinuous,secondary,f,f,t,EUT
6155,1020,t,f,0.000000,3,1ºtrimester,t,1,clear,2,...,1.48,50.0,23.28,41,continuous,primary,f,f,f,emergencyc-section
6156,2002,f,f,0.000000,0,1ºtrimester,f,2,clear,0,...,1.65,75.2,24.00,32,discontinuous,Sinestudios,f,f,f,EUT

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

#ml_df.Publisher = ml_df.Publisher.astype(str)

for column in ml_df.columns:
    temp_new = le.fit_transform(ml_df[column].astype('category'))
    ml_df.drop(labels=[column], axis="columns", inplace=True)
    ml_df[column] = temp_new

X = ml_df.loc[:,'PARITY':'ALCOHOL']
Y = ml_df.loc[:,'TYPEOFBIRTH':]

In [ ]:
from imblearn.over_sampling import ADASYN 
sm = ADASYN(sampling_strategy='auto', random_state=None, n_neighbors=5, n_jobs=1)
X_adassin_1, Y_adassin_1 = sm.fit_resample(X, Y)
print(X_adassin_1.shape)
print(Y_adassin_1.shape)

(29493, 21)
(29493, 1)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_adassin_1,Y_adassin_1,test_size=0.2,random_state=None)

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23594 entries, 28733 to 23261
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PARITY                   23594 non-null  int64
 1   OBSTETRICRISK            23594 non-null  int64
 2   COMORBIDITY              23594 non-null  int64
 3   NUMBEROFPREVCESAREAN     23594 non-null  int64
 4   KGINCREASEDPREGNANCY     23594 non-null  int64
 5   STARTANTENATALCARRE      23594 non-null  int64
 6   ART                      23594 non-null  int64
 7   PREVIOUSTERMPREGNANCIES  23594 non-null  int64
 8   AMNIOTICLIQUID           23594 non-null  int64
 9   MISCARRIAGES             23594 non-null  int64
 10  ANESTHESIA               23594 non-null  int64
 11  GESTAGIONALAGE           23594 non-null  int64
 12  HEIGHT                   23594 non-null  int64
 13  WEIGHT                   23594 non-null  int64
 14  BMI                      23594 non-null  int64
 15  AGE                      23594 non-null  int64
 16  CARDIOTOCOGRAPHY         23594 non-null  int64
 17  MATERNALEDUCATION        23594 non-null  int64
 18  SUBSTANCEABUSE           23594 non-null  int64
 19  SMOKING                  23594 non-null  int64
 20  ALCOHOL                  23594 non-null  int64
dtypes: int64(21)
memory usage: 4.0 MB

In [ ]:
Y_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23594 entries, 28733 to 23261
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TYPEOFBIRTH  23594 non-null  int64
dtypes: int64(1)
memory usage: 368.7 KB

In [ ]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5899 entries, 20447 to 25603
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   PARITY                   5899 non-null   int64
 1   OBSTETRICRISK            5899 non-null   int64
 2   COMORBIDITY              5899 non-null   int64
 3   NUMBEROFPREVCESAREAN     5899 non-null   int64
 4   KGINCREASEDPREGNANCY     5899 non-null   int64
 5   STARTANTENATALCARRE      5899 non-null   int64
 6   ART                      5899 non-null   int64
 7   PREVIOUSTERMPREGNANCIES  5899 non-null   int64
 8   AMNIOTICLIQUID           5899 non-null   int64
 9   MISCARRIAGES             5899 non-null   int64
 10  ANESTHESIA               5899 non-null   int64
 11  GESTAGIONALAGE           5899 non-null   int64
 12  HEIGHT                   5899 non-null   int64
 13  WEIGHT                   5899 non-null   int64
 14  BMI                      5899 non-null   int64
 15  AGE                      5899 non-null   int64
 16  CARDIOTOCOGRAPHY         5899 non-null   int64
 17  MATERNALEDUCATION        5899 non-null   int64
 18  SUBSTANCEABUSE           5899 non-null   int64
 19  SMOKING                  5899 non-null   int64
 20  ALCOHOL                  5899 non-null   int64
dtypes: int64(21)
memory usage: 1013.9 KB

In [ ]:
Y_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5899 entries, 20447 to 25603
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   TYPEOFBIRTH  5899 non-null   int64
dtypes: int64(1)
memory usage: 92.2 KB

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
model = DecisionTreeClassifier(criterion = 'entropy')
model.fit(X_train,Y_train)
y_pred = model.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

0.8243770130530599
0.8187907696818021
0.8243770130530599
0.8243770130530599

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier()
RFC.fit(X_train, Y_train.values.ravel())
y_pred = RFC.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

0.9250720461095101
0.9234924365608426
0.9250720461095101
0.9250720461095101

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
svc = SVC(gamma = 0.001, C = 1000)
y_pred = svc.fit(X_train, Y_train.values.ravel()).predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

0.9249025258518393
0.9229137411431964
0.9249025258518393
0.9249025258518393

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
K = []
training = []
test = []
scores = {}
  
for k in range(2, 21):
    clf = KNeighborsClassifier(n_neighbors = k)
    clf.fit(X_train, Y_train.values.ravel())
  
    training_score = clf.score(X_train, Y_train)
    test_score = clf.score(X_test, Y_test)
    K.append(k)
  
    training.append(training_score)
    test.append(test_score)
    scores[k] = [training_score, test_score]
for keys, values in scores.items():
    print(keys, ':', values)

2 : [0.9438416546579639, 0.8313273436175623]
3 : [0.9085360684919895, 0.8274283776911341]
4 : [0.8810290751886073, 0.804712663163248]
5 : [0.8595405611596169, 0.7952195287336836]
6 : [0.8403831482580317, 0.7764027801322259]
7 : [0.8224548614054421, 0.7638582810645872]
8 : [0.8080444180723912, 0.7516528225122903]
9 : [0.7932101381707214, 0.7453805729784709]
10 : [0.7811731796219378, 0.7343617562298694]
11 : [0.769220988386878, 0.7238515002542804]
12 : [0.7569721115537849, 0.7092727580945923]
13 : [0.749003984063745, 0.704695711137481]
14 : [0.7379842332796474, 0.6967282590269537]
15 : [0.730270407730779, 0.6880827258857434]
16 : [0.7202254810545053, 0.6804543142905577]
17 : [0.7121302025938798, 0.6741820647567385]
18 : [0.7060693396626261, 0.6668926936768944]
19 : [0.6988641179961007, 0.6602814036277335]
20 : [0.6938628464863948, 0.654178674351585]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=2,weights='distance',p=1)
model.fit(X_train,Y_train.values.ravel())
y_pred = model.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

0.9003220884895745
0.8988482786773968
0.9003220884895745
0.9003220884895745

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [ ]:
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import StackingClassifier
estimators = [('rf', RandomForestClassifier()),('svr', make_pipeline(StandardScaler(),LinearSVC())),('dt',DecisionTreeClassifier(criterion = 'entropy')),('knn',KNeighborsClassifier(n_neighbors=2,weights='distance',p=1))]
clf = StackingClassifier(estimators=estimators, final_estimator=LogisticRegression())
clf.fit(X_train, Y_train.values.ravel())
y_pred = clf.predict(X_test)
print(accuracy_score(Y_test,y_pred))
print(precision_score(Y_test,y_pred,pos_label='positive',average='weighted'))
print(recall_score(Y_test,y_pred,pos_label='positive',average='micro'))
print(f1_score(Y_test, y_pred,average='micro'))

/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/svm/_base.py:1208: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  ConvergenceWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

0.955246651974911
0.9551059051547031
0.955246651974911
0.955246651974911

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,